import { CustomerMenuData } from '@/types/customer.types';
import idli from '../assets/images/food/idli.jpg';
import pongal from '../assets/images/food/pongal.jpg';
import dosa from '../assets/images/food/dosa.png';
import masalaDosa from '../assets/images/food/masala-dosa.jpg';
import onionDosa from '../assets/images/food/onion-dosa.jpg';
import onionUthappam from '../assets/images/food/onion-uthappam.jpg';
import gheeRoast from '../assets/images/food/ghee-roast.jpg';
import podiDosa from '../assets/images/food/podi-dosa.jpg';
import uthappam from '../assets/images/food/uthappam.png';
import eggDosa from '../assets/images/food/egg-dosa.jpg';
import parotta from '../assets/images/food/parotta.jpg';
import vegKothu from '../assets/images/food/veg-kothu.jpg';
import eggKothu from '../assets/images/food/egg-kothu.jpg';
import paneerKothu from '../assets/images/food/paneer-kothu.jpg';
import paneerDosa from '../assets/images/food/paneer-dosa.jpg';
import ceylonDhamParotta from '../assets/images/food/ceylon-dham-parotta.jpg';
import poori from '../assets/images/food/poori.jpg';
import chapati from '../assets/images/food/chapati.jpg';
import tomatoRice from '../assets/images/food/tomato-rice.jpg';
import omelette from '../assets/images/food/omelette.jpg';
import halfBoil from '../assets/images/food/half-boil.jpg';
import kalakki from '../assets/images/food/kalakki.jpg';
import puliyodharai from '../assets/images/food/puliyodharai.jpg';
import mushroomBiryani from '../assets/images/food/mushroom-biryani.jpg';
import ravaDosa from '../assets/images/food/rava-dosa.jpg';
import defaultTiffin from '../assets/images/food/default-food.png';
import defaultParotta from '../assets/images/food/default-food.png';
import defaultRice from '../assets/images/food/default-food.png';
import defaultDosa from '../assets/images/food/default-food.png';
import defaultFood from '../assets/images/food/default-food.png';

export const DEFAULT_IMAGES = {
  tiffin: defaultTiffin,
  parotta: defaultParotta,
  rice: defaultRice,
  dosa: defaultDosa,
  default: defaultFood,
};

export const getCustomerMenuData = (restaurantId: string): CustomerMenuData => {
    console.log('Fetching menu data for restaurant ID:', restaurantId);
  return {
    restaurant: {
      id: '1',
      name: 'Hotel Srinivas',
      nameTamil: 'ஹோட்டல் ஸ்ரீனிவாஸ்',
      primaryColor: '#D32F2F',
      phone: '+91 98765 43210',
      address: 'Thiruppathi Nagar, APK Main Road, Avaniapuram, Madurai - 625012',
      addressTamil: 'திருப்பதி நகர், APK மெயின் ரோடு, அவனியாபுரம், மதுரை - 625012',
      timings: {
        morning: { start: '7:00 AM', end: '11:30 AM' },
        evening: { start: '6:30 PM', end: '10:30 PM' },
      },
    },
    categories: [
      { id: '1', name: 'Dosa Varieties', nameTamil: 'தோசை வகைகள்', availableTimes: ['morning', 'evening'], defaultImage: DEFAULT_IMAGES.dosa },
      { id: '2', name: 'Idli & Pongal', nameTamil: 'இட்லி & பொங்கல்', availableTimes: ['morning', 'evening'], defaultImage: DEFAULT_IMAGES.tiffin },
      { id: '3', name: 'Parotta Varieties', nameTamil: 'பரோட்டா வகைகள்', availableTimes: ['evening'], defaultImage: DEFAULT_IMAGES.parotta },
    ],
    items: [
      // Idli & Pongal Category
  {
    id: '1',
    name: 'Idli',
    nameTamil: 'இட்லி',
    description: 'Soft steamed rice cakes served with sambar and chutney',
    descriptionTamil: 'சாம்பார் மற்றும் சட்னியுடன் பரிமாறப்படும் மென்மையான இட்லி',
    price: 10,
    categoryId: '2',
    imageUrl: idli,
    isChefsSpecial: false,
    isTodaysSpecial: false,
    isSeasonal: false,
    isVeg: true,
    spiceLevel: 0,
    availableTimes: ['morning', 'evening'],
    ingredients: ['Rice', 'Urad Dal', 'Salt', 'Fenugreek Seeds'],
    ingredientsTamil: ['அரிசி', 'உளுந்து', 'உப்பு', 'வெந்தயம்'],
    nutrition: {
      protein: '2.5g',
      carbs: '12g',
      fat: '0.5g',
      calories: '60 kcal',
      fiber: '1g',
    },
    preparationTime: '20 mins',
    servingSize: '1 piece (40g)',
  },
  {
    id: '2',
    name: 'Ven Pongal',
    nameTamil: 'வெண் பொங்கல்',
    description: 'Savory rice and lentil porridge tempered with ghee, pepper and cumin',
    descriptionTamil: 'நெய், மிளகு மற்றும் சீரகத்துடன் தாளிக்கப்பட்ட அரிசி பருப்பு கஞ்சி',
    price: 40,
    categoryId: '2',
    imageUrl: pongal,
    isChefsSpecial: true,
    isTodaysSpecial: false,
    isSeasonal: false,
    isVeg: true,
    spiceLevel: 1,
    availableTimes: ['morning'],
    ingredients: ['Rice', 'Moong Dal', 'Ghee', 'Black Pepper', 'Cumin', 'Cashews', 'Curry Leaves'],
    ingredientsTamil: ['அரிசி', 'பாசிப்பருப்பு', 'நெய்', 'மிளகு', 'சீரகம்', 'முந்திரி', 'கறிவேப்பிலை'],
    nutrition: {
      protein: '8g',
      carbs: '45g',
      fat: '12g',
      calories: '320 kcal',
      fiber: '3g',
    },
    preparationTime: '30 mins',
    servingSize: '1 plate (250g)',
  },

  // Dosa Varieties
  {
    id: '3',
    name: 'Dosa',
    nameTamil: 'தோசை',
    description: 'Crispy thin rice crepe served with sambar and chutney',
    descriptionTamil: 'சாம்பார் மற்றும் சட்னியுடன் பரிமாறப்படும் மொறுமொறுப்பான தோசை',
    price: 40,
    categoryId: '1',
    imageUrl: dosa,
    isChefsSpecial: false,
    isTodaysSpecial: false,
    isSeasonal: false,
    isVeg: true,
    spiceLevel: 1,
    availableTimes: ['morning', 'evening'],
    ingredients: ['Rice', 'Urad Dal', 'Fenugreek Seeds', 'Salt', 'Oil'],
    ingredientsTamil: ['அரிசி', 'உளுந்து', 'வெந்தயம்', 'உப்பு', 'எண்ணெய்'],
    nutrition: {
      protein: '4g',
      carbs: '28g',
      fat: '3g',
      calories: '150 kcal',
      fiber: '2g',
    },
    preparationTime: '15 mins',
    servingSize: '1 dosa (80g)',
  },
  {
    id: '4',
    name: 'Masala Dosa',
    nameTamil: 'மசாலா தோசை',
    description: 'Crispy dosa filled with spiced potato masala',
    descriptionTamil: 'மசால் உருளைக்கிழங்கு நிரப்பிய மொறுமொறுப்பான தோசை',
    price: 60,
    categoryId: '1',
    imageUrl: masalaDosa,
    isChefsSpecial: true,
    isTodaysSpecial: false,
    isSeasonal: false,
    isVeg: true,
    spiceLevel: 2,
    availableTimes: ['morning'],
    ingredients: ['Dosa Batter', 'Potato', 'Onion', 'Green Chili', 'Turmeric', 'Mustard Seeds', 'Curry Leaves'],
    ingredientsTamil: ['தோசை மாவு', 'உருளைக்கிழங்கு', 'வெங்காயம்', 'பச்சை மிளகாய்', 'மஞ்சள்', 'கடுகு', 'கறிவேப்பிலை'],
    nutrition: {
      protein: '6g',
      carbs: '42g',
      fat: '8g',
      calories: '260 kcal',
      fiber: '4g',
    },
    preparationTime: '20 mins',
    servingSize: '1 dosa with masala (150g)',
  },
  {
    id: '5',
    name: 'Onion Dosa',
    nameTamil: 'ஆனியன் தோசை',
    description: 'Crispy dosa topped with finely chopped onions',
    descriptionTamil: 'பொடியாக நறுக்கிய வெங்காயத்துடன் மொறுமொறுப்பான தோசை',
    price: 60,
    categoryId: '1',
    imageUrl: onionDosa,
    isChefsSpecial: false,
    isTodaysSpecial: true,
    isSeasonal: false,
    isVeg: true,
    spiceLevel: 2,
    availableTimes: ['morning', 'evening'],
    ingredients: ['Dosa Batter', 'Onion', 'Green Chili', 'Coriander', 'Oil'],
    ingredientsTamil: ['தோசை மாவு', 'வெங்காயம்', 'பச்சை மிளகாய்', 'கொத்தமல்லி', 'எண்ணெய்'],
    nutrition: {
      protein: '5g',
      carbs: '32g',
      fat: '5g',
      calories: '190 kcal',
      fiber: '3g',
    },
    preparationTime: '15 mins',
    servingSize: '1 dosa (100g)',
  },
  {
    id: '6',
    name: 'Onion Uthappam',
    nameTamil: 'ஆனியன் ஊத்தப்பம்',
    description: 'Thick pancake with onions and spices',
    descriptionTamil: 'வெங்காயம் மற்றும் மசாலாப் பொருட்களுடன் தடித்த பான்கேக்',
    price: 60,
    categoryId: '1',
    imageUrl: onionUthappam,
    isChefsSpecial: false,
    isTodaysSpecial: false,
    isSeasonal: false,
    isVeg: true,
    spiceLevel: 2,
    availableTimes: ['morning', 'evening'],
    ingredients: ['Dosa Batter', 'Onion', 'Tomato', 'Green Chili', 'Coriander'],
    ingredientsTamil: ['தோசை மாவு', 'வெங்காயம்', 'தக்காளி', 'பச்சை மிளகாய்', 'கொத்தமல்லி'],
    nutrition: {
      protein: '6g',
      carbs: '35g',
      fat: '4g',
      calories: '200 kcal',
      fiber: '3g',
    },
    preparationTime: '20 mins',
    servingSize: '1 uthappam (120g)',
  },
  {
    id: '7',
    name: 'Ghee Roast',
    nameTamil: 'நெய் ரோஸ்ட்',
    description: 'Crispy dosa roasted with ghee for extra flavor',
    descriptionTamil: 'கூடுதல் சுவைக்காக நெய்யில் வறுத்த மொறுமொறுப்பான தோசை',
    price: 60,
    categoryId: '1',
    imageUrl: gheeRoast,
    isChefsSpecial: true,
    isTodaysSpecial: false,
    isSeasonal: false,
    isVeg: true,
    spiceLevel: 1,
    availableTimes: ['morning', 'evening'],
    ingredients: ['Dosa Batter', 'Ghee', 'Salt'],
    ingredientsTamil: ['தோசை மாவு', 'நெய்', 'உப்பு'],
    nutrition: {
      protein: '4g',
      carbs: '30g',
      fat: '10g',
      calories: '220 kcal',
      fiber: '2g',
    },
    preparationTime: '15 mins',
    servingSize: '1 dosa (90g)',
  },
  {
    id: '8',
    name: 'Podi Dosa',
    nameTamil: 'பொடி தோசை',
    description: 'Crispy dosa with spicy lentil powder and ghee',
    descriptionTamil: 'காரமான பருப்பு பொடி மற்றும் நெய்யுடன் மொறுமொறுப்பான தோசை',
    price: 50,
    categoryId: '1',
    imageUrl: podiDosa,
    isChefsSpecial: false,
    isTodaysSpecial: false,
    isSeasonal: false,
    isVeg: true,
    spiceLevel: 3,
    availableTimes: ['morning', 'evening'],
    ingredients: ['Dosa Batter', 'Gun Powder (Idli Podi)', 'Ghee', 'Oil'],
    ingredientsTamil: ['தோசை மாவு', 'மிளகாய் பொடி', 'நெய்', 'எண்ணெய்'],
    nutrition: {
      protein: '5g',
      carbs: '32g',
      fat: '8g',
      calories: '210 kcal',
      fiber: '3g',
    },
    preparationTime: '15 mins',
    servingSize: '1 dosa (95g)',
  },
  {
    id: '9',
    name: 'Uthappam',
    nameTamil: 'ஊத்தப்பம்',
    description: 'Thick fluffy pancake made with dosa batter',
    descriptionTamil: 'தோசை மாவில் செய்யப்பட்ட தடித்த பஞ்சுப்பான பான்கேக்',
    price: 40,
    categoryId: '1',
    imageUrl: uthappam,
    isChefsSpecial: false,
    isTodaysSpecial: false,
    isSeasonal: false,
    isVeg: true,
    spiceLevel: 1,
    availableTimes: ['morning', 'evening'],
    ingredients: ['Dosa Batter', 'Oil', 'Salt'],
    ingredientsTamil: ['தோசை மாவு', 'எண்ணெய்', 'உப்பு'],
    nutrition: {
      protein: '5g',
      carbs: '33g',
      fat: '3g',
      calories: '180 kcal',
      fiber: '2g',
    },
    preparationTime: '15 mins',
    servingSize: '1 uthappam (100g)',
  },
  {
    id: '10',
    name: 'Egg Dosa',
    nameTamil: 'முட்டை தோசை',
    description: 'Dosa topped with beaten egg and spices',
    descriptionTamil: 'அடித்த முட்டை மற்றும் மசாலாப் பொருட்களுடன் தோசை',
    price: 60,
    categoryId: '1',
    imageUrl: eggDosa,
    isChefsSpecial: false,
    isTodaysSpecial: false,
    isSeasonal: false,
    isVeg: false,
    spiceLevel: 2,
    availableTimes: ['morning', 'evening'],
    ingredients: ['Dosa Batter', 'Egg', 'Onion', 'Green Chili', 'Coriander', 'Oil'],
    ingredientsTamil: ['தோசை மாவு', 'முட்டை', 'வெங்காயம்', 'பச்சை மிளகாய்', 'கொத்தமல்லி', 'எண்ணெய்'],
    nutrition: {
      protein: '10g',
      carbs: '30g',
      fat: '12g',
      calories: '270 kcal',
      fiber: '2g',
    },
    preparationTime: '20 mins',
    servingSize: '1 dosa with egg (130g)',
  },

  // Parotta Varieties (Evening only)
  {
    id: '11',
    name: 'Parotta',
    nameTamil: 'பரோட்டா',
    description: 'Flaky layered flatbread',
    descriptionTamil: 'அடுக்கு அடுக்காக செய்யப்பட்ட மென்மையான ரொட்டி',
    price: 15,
    categoryId: '3',
    imageUrl: parotta,
    isChefsSpecial: false,
    isTodaysSpecial: false,
    isSeasonal: false,
    isVeg: true,
    spiceLevel: 0,
    availableTimes: ['evening'],
    ingredients: ['All Purpose Flour', 'Oil', 'Salt', 'Water'],
    ingredientsTamil: ['மைதா', 'எண்ணெய்', 'உப்பு', 'தண்ணீர்'],
    nutrition: {
      protein: '3g',
      carbs: '22g',
      fat: '5g',
      calories: '145 kcal',
      fiber: '1g',
    },
    preparationTime: '25 mins',
    servingSize: '1 parotta (70g)',
  },
  {
    id: '12',
    name: 'Veg Kothu Parotta',
    nameTamil: 'வெஜ் கொத்து பரோட்டா',
    description: 'Shredded parotta stir-fried with vegetables and spices',
    descriptionTamil: 'காய்கறிகள் மற்றும் மசாலாப் பொருட்களுடன் வறுக்கப்பட்ட பரோட்டா துண்டுகள்',
    price: 70,
    categoryId: '3',
    imageUrl: vegKothu,
    isChefsSpecial: true,
    isTodaysSpecial: false,
    isSeasonal: false,
    isVeg: true,
    spiceLevel: 3,
    availableTimes: ['evening'],
    ingredients: ['Parotta', 'Mixed Vegetables', 'Onion', 'Tomato', 'Ginger-Garlic', 'Spices', 'Curry Leaves'],
    ingredientsTamil: ['பரோட்டா', 'கலவை காய்கறிகள்', 'வெங்காயம்', 'தக்காளி', 'இஞ்சி-பூண்டு', 'மசாலா', 'கறிவேப்பிலை'],
    nutrition: {
      protein: '8g',
      carbs: '52g',
      fat: '18g',
      calories: '400 kcal',
      fiber: '5g',
    },
    preparationTime: '30 mins',
    servingSize: '1 plate (280g)',
  },
  {
    id: '13',
    name: 'Egg Kothu Parotta',
    nameTamil: 'முட்டை கொத்து பரோட்டா',
    description: 'Shredded parotta stir-fried with eggs and spices',
    descriptionTamil: 'முட்டை மற்றும் மசாலாப் பொருட்களுடன் வறுக்கப்பட்ட பரோட்டா துண்டுகள்',
    price: 90,
    categoryId: '3',
    imageUrl: eggKothu,
    isChefsSpecial: true,
    isTodaysSpecial: true,
    isSeasonal: false,
    isVeg: false,
    spiceLevel: 3,
    availableTimes: ['evening'],
    ingredients: ['Parotta', 'Egg', 'Onion', 'Tomato', 'Ginger-Garlic', 'Spices', 'Curry Leaves'],
    ingredientsTamil: ['பரோட்டா', 'முட்டை', 'வெங்காயம்', 'தக்காளி', 'இஞ்சி-பூண்டு', 'மசாலா', 'கறிவேப்பிலை'],
    nutrition: {
      protein: '15g',
      carbs: '50g',
      fat: '22g',
      calories: '470 kcal',
      fiber: '4g',
    },
    preparationTime: '30 mins',
    servingSize: '1 plate (300g)',
  },
  {
    id: '14',
    name: 'Paneer Veg Kothu',
    nameTamil: 'பன்னீர் வெஜ் கொத்து',
    description: 'Shredded parotta with paneer and vegetables',
    descriptionTamil: 'பன்னீர் மற்றும் காய்கறிகளுடன் கொத்து பரோட்டா',
    price: 90,
    categoryId: '3',
    imageUrl: paneerKothu,
    isChefsSpecial: true,
    isTodaysSpecial: false,
    isSeasonal: false,
    isVeg: true,
    spiceLevel: 3,
    availableTimes: ['evening'],
    ingredients: ['Parotta', 'Paneer', 'Mixed Vegetables', 'Onion', 'Tomato', 'Spices'],
    ingredientsTamil: ['பரோட்டா', 'பன்னீர்', 'கலவை காய்கறிகள்', 'வெங்காயம்', 'தக்காளி', 'மசாலா'],
    nutrition: {
      protein: '16g',
      carbs: '48g',
      fat: '20g',
      calories: '450 kcal',
      fiber: '5g',
    },
    preparationTime: '35 mins',
    servingSize: '1 plate (320g)',
  },
  {
    id: '15',
    name: 'Paneer Masala Dosa',
    nameTamil: 'பன்னீர் மசால் தோசை',
    description: 'Crispy dosa filled with spiced paneer masala',
    descriptionTamil: 'மசால் பன்னீர் நிரப்பிய மொறுமொறுப்பான தோசை',
    price: 60,
    categoryId: '1',
    imageUrl: paneerDosa,
    isChefsSpecial: false,
    isTodaysSpecial: false,
    isSeasonal: false,
    isVeg: true,
    spiceLevel: 2,
    availableTimes: ['evening'],
    ingredients: ['Dosa Batter', 'Paneer', 'Onion', 'Tomato', 'Green Chili', 'Spices'],
    ingredientsTamil: ['தோசை மாவு', 'பன்னீர்', 'வெங்காயம்', 'தக்காளி', 'பச்சை மிளகாய்', 'மசாலா'],
    nutrition: {
      protein: '12g',
      carbs: '40g',
      fat: '14g',
      calories: '340 kcal',
      fiber: '3g',
    },
    preparationTime: '25 mins',
    servingSize: '1 dosa (180g)',
  },
  {
    id: '16',
    name: 'Ceylon Dum Parotta',
    nameTamil: 'சிலோன் தம் பரோட்டா',
    description: 'Special parotta with Ceylon spices',
    descriptionTamil: 'இலங்கை மசாலாவுடன் சிறப்பு பரோட்டா',
    price: 90,
    categoryId: '3',
    imageUrl: ceylonDhamParotta,
    isChefsSpecial: true,
    isTodaysSpecial: false,
    isSeasonal: false,
    isVeg: true,
    spiceLevel: 3,
    availableTimes: ['evening'],
    ingredients: ['Parotta', 'Ceylon Spice Mix', 'Coconut', 'Curry Leaves', 'Special Gravy'],
    ingredientsTamil: ['பரோட்டா', 'இலங்கை மசாலா', 'தேங்காய்', 'கறிவேப்பிலை', 'சிறப்பு குழம்பு'],
    nutrition: {
      protein: '9g',
      carbs: '55g',
      fat: '20g',
      calories: '440 kcal',
      fiber: '4g',
    },
    preparationTime: '40 mins',
    servingSize: '1 plate (300g)',
  },

  // Special Items
  {
    id: '17',
    name: 'Poori (1-set)',
    nameTamil: 'பூரி (1-செட்)',
    description: 'Deep-fried puffed bread served with potato masala',
    descriptionTamil: 'உருளைக்கிழங்கு மசாலாவுடன் பொரித்த ரொட்டி',
    price: 40,
    categoryId: '5',
    imageUrl: poori,
    isChefsSpecial: false,
    isTodaysSpecial: false,
    isSeasonal: false,
    isVeg: true,
    spiceLevel: 1,
    availableTimes: ['morning'],
    ingredients: ['Wheat Flour', 'Oil', 'Salt', 'Potato', 'Spices'],
    ingredientsTamil: ['கோதுமை மாவு', 'எண்ணெய்', 'உப்பு', 'உருளைக்கிழங்கு', 'மசாலா'],
    nutrition: {
      protein: '7g',
      carbs: '48g',
      fat: '15g',
      calories: '350 kcal',
      fiber: '4g',
    },
    preparationTime: '25 mins',
    servingSize: '3 pooris with masala (180g)',
  },
  {
    id: '18',
    name: 'Chapathi (1-set)',
    nameTamil: 'சப்பாத்தி (1-செட்)',
    description: 'Soft whole wheat flatbread served with kurma',
    descriptionTamil: 'குருமாவுடன் பரிமாறப்படும் மென்மையான கோதுமை ரொட்டி',
    price: 40,
    categoryId: '5',
    imageUrl: chapati,
    isChefsSpecial: false,
    isTodaysSpecial: false,
    isSeasonal: false,
    isVeg: true,
    spiceLevel: 2,
    availableTimes: ['morning', 'evening'],
    ingredients: ['Wheat Flour', 'Oil', 'Salt', 'Water', 'Vegetable Kurma'],
    ingredientsTamil: ['கோதுமை மாவு', 'எண்ணெய்', 'உப்பு', 'தண்ணீர்', 'காய்கறி குருமா'],
    nutrition: {
      protein: '8g',
      carbs: '45g',
      fat: '10g',
      calories: '310 kcal',
      fiber: '6g',
    },
    preparationTime: '30 mins',
    servingSize: '3 chapatis with kurma (220g)',
  },
  {
    id: '19',
    name: 'Tomato Rice',
    nameTamil: 'தக்காளி சாதம்',
    description: 'Tangy tomato rice with aromatic spices',
    descriptionTamil: 'நறுமண மசாலாப் பொருட்களுடன் புளிப்பு தக்காளி சாதம்',
    price: 50,
    categoryId: '4',
    imageUrl: tomatoRice,
    isChefsSpecial: false,
    isTodaysSpecial: false,
    isSeasonal: false,
    isVeg: true,
    spiceLevel: 2,
    availableTimes: ['evening'],
    ingredients: ['Rice', 'Tomato', 'Onion', 'Spices', 'Curry Leaves', 'Peanuts'],
    ingredientsTamil: ['அரிசி', 'தக்காளி', 'வெங்காயம்', 'மசாலா', 'கறிவேப்பிலை', 'கடலை'],
    nutrition: {
      protein: '6g',
      carbs: '50g',
      fat: '8g',
      calories: '290 kcal',
      fiber: '4g',
    },
    preparationTime: '30 mins',
    servingSize: '1 plate (250g)',
  },
  {
    id: '20',
    name: 'Omelette',
    nameTamil: 'ஆம்லெட்',
    description: 'Fluffy egg omelette with onions and spices',
    descriptionTamil: 'வெங்காயம் மற்றும் மசாலாவுடன் பஞ்சுப்பான முட்டை ஆம்லெட்',
    price: 20,
    categoryId: '5',
    imageUrl: omelette,
    isChefsSpecial: false,
    isTodaysSpecial: false,
    isSeasonal: false,
    isVeg: false,
    spiceLevel: 2,
    availableTimes: ['morning', 'evening'],
    ingredients: ['Egg', 'Onion', 'Green Chili', 'Tomato', 'Coriander', 'Oil'],
    ingredientsTamil: ['முட்டை', 'வெங்காயம்', 'பச்சை மிளகாய்', 'தக்காளி', 'கொத்தமல்லி', 'எண்ணெய்'],
    nutrition: {
      protein: '12g',
      carbs: '3g',
      fat: '14g',
      calories: '180 kcal',
      fiber: '1g',
    },
    preparationTime: '10 mins',
    servingSize: '1 omelette (100g)',
  },
  {
    id: '21',
    name: 'Half Boil',
    nameTamil: 'ஹாஃப் பாயில்',
    description: 'Soft boiled egg with runny yolk',
    descriptionTamil: 'ஓடும் மஞ்சள் கருவுடன் மென்மையாக வேகவைத்த முட்டை',
    price: 15,
    categoryId: '5',
    imageUrl: halfBoil,
    isChefsSpecial: false,
    isTodaysSpecial: false,
    isSeasonal: false,
    isVeg: false,
    spiceLevel: 0,
    availableTimes: ['morning', 'evening'],
    ingredients: ['Egg', 'Salt', 'Pepper'],
    ingredientsTamil: ['முட்டை', 'உப்பு', 'மிளகு'],
    nutrition: {
      protein: '6g',
      carbs: '1g',
      fat: '5g',
      calories: '70 kcal',
      fiber: '0g',
    },
    preparationTime: '5 mins',
    servingSize: '1 egg (50g)',
  },
  {
    id: '22',
    name: 'Kalakki',
    nameTamil: 'கலக்கி',
    description: 'Traditional mixed millet porridge',
    descriptionTamil: 'பாரம்பரிய கலவை தினை கஞ்சி',
    price: 25,
    categoryId: '5',
    imageUrl: kalakki,
    isChefsSpecial: false,
    isTodaysSpecial: false,
    isSeasonal: false,
    isVeg: true,
    spiceLevel: 1,
    availableTimes: ['evening'],
    ingredients: ['Mixed Millets', 'Jaggery', 'Cardamom', 'Milk'],
    ingredientsTamil: ['கலவை தினை', 'வெல்லம்', 'ஏலக்காய்', 'பால்'],
    nutrition: {
      protein: '4g',
      carbs: '38g',
      fat: '2g',
      calories: '180 kcal',
      fiber: '5g',
    },
    preparationTime: '35 mins',
    servingSize: '1 cup (200ml)',
  },
  {
    id: '23',
    name: 'Puliyodharai',
    nameTamil: 'புளியோதரை',
    description: 'Tangy tamarind rice with peanuts and spices',
    descriptionTamil: 'வேர்க்கடலை மற்றும் மசாலாவுடன் புளிப்பு புளி சாதம்',
    price: 40,
    categoryId: '4',
    imageUrl: puliyodharai,
    isChefsSpecial: false,
    isTodaysSpecial: false,
    isSeasonal: false,
    isVeg: true,
    spiceLevel: 2,
    availableTimes: ['evening'],
    ingredients: ['Rice', 'Tamarind', 'Peanuts', 'Sesame Seeds', 'Spices', 'Curry Leaves'],
    ingredientsTamil: ['அரிசி', 'புளி', 'கடலை', 'எள்', 'மசாலா', 'கறிவேப்பிலை'],
    nutrition: {
      protein: '7g',
      carbs: '52g',
      fat: '10g',
      calories: '320 kcal',
      fiber: '5g',
    },
    preparationTime: '30 mins',
    servingSize: '1 plate (250g)',
  },
  {
    id: '24',
    name: 'Mushroom Biryani',
    nameTamil: 'காளான் பிரியாணி',
    description: 'Fragrant mushroom biryani with aromatic spices',
    descriptionTamil: 'நறுமண மசாலாப் பொருட்களுடன் காளான் பிரியாணி',
    price: 60,
    categoryId: '4',
    imageUrl: mushroomBiryani,
    isChefsSpecial: true,
    isTodaysSpecial: false,
    isSeasonal: false,
    isVeg: true,
    spiceLevel: 3,
    availableTimes: ['evening'],
    ingredients: ['Basmati Rice', 'Mushroom', 'Yogurt', 'Spices', 'Onion', 'Mint', 'Coriander'],
    ingredientsTamil: ['பாஸ்மதி அரிசி', 'காளான்', 'தயிர்', 'மசாலா', 'வெங்காயம்', 'புதினா', 'கொத்தமல்லி'],
    nutrition: {
      protein: '10g',
      carbs: '58g',
      fat: '12g',
      calories: '380 kcal',
      fiber: '4g',
    },
    preparationTime: '45 mins',
    servingSize: '1 plate (300g)',
  },
  {
    id: '25',
    name: 'Rava Dosa',
    nameTamil: 'ரவா தோசை',
    description: 'Crispy semolina crepe with onions and chilies',
    descriptionTamil: 'வெங்காயம் மற்றும் மிளகாயுடன் மொறுமொறுப்பான ரவை தோசை',
    price: 60,
    categoryId: '1',
    imageUrl: ravaDosa,
    isChefsSpecial: false,
    isTodaysSpecial: false,
    isSeasonal: false,
    isVeg: true,
    spiceLevel: 2,
    availableTimes: ['evening'],
    ingredients: ['Rava (Semolina)', 'Rice Flour', 'Onion', 'Green Chili', 'Curry Leaves', 'Cumin'],
    ingredientsTamil: ['ரவை', 'அரிசி மாவு', 'வெங்காயம்', 'பச்சை மிளகாய்', 'கறிவேப்பிலை', 'சீரகம்'],
    nutrition: {
      protein: '5g',
      carbs: '34g',
      fat: '6g',
      calories: '210 kcal',
      fiber: '2g',
    },
    preparationTime: '20 mins',
    servingSize: '1 dosa (110g)',
  },
    ],
    advertisements: [
      {
        id: '1',
        title: 'Fresh Hot Breakfast',
        titleTamil: 'புதிய சூடான காலை உணவு',
        subtitle: 'Authentic South Indian Tiffin Items',
        subtitleTamil: 'உண்மையான தென்னிந்திய டிபன் உணவுகள்',
        image: '/images/ads/breakfast-banner.jpg',
        backgroundColor: '#FFF3E0',
        textColor: '#E65100',
      },
    ],
  };
};