import { ThemePreset } from '@/types/dashboard.types';

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'classic-orange',
    name: 'Classic Orange',
    nameTamil: 'கிளாசிக் ஆரஞ்சு',
    colors: {
      primary: '#f97316',
      secondary: '#ea580c',
      background: '#ffffff',
      text: '#1f2937',
      heading: '#111827',
      border: '#e5e7eb',
      highlight: '#fbbf24',
      success: '#10b981',
      warning: '#f59e0b',
      danger: '#ef4444',
    },
  },
  {
    id: 'traditional-red',
    name: 'Traditional Red',
    nameTamil: 'பாரம்பரிய சிவப்பு',
    colors: {
      primary: '#dc2626',
      secondary: '#991b1b',
      background: '#fef2f2',
      text: '#1f2937',
      heading: '#7f1d1d',
      border: '#fecaca',
      highlight: '#fbbf24',
      success: '#10b981',
      warning: '#f59e0b',
      danger: '#ef4444',
    },
  },
  {
    id: 'modern-blue',
    name: 'Modern Blue',
    nameTamil: 'நவீன நீலம்',
    colors: {
      primary: '#2563eb',
      secondary: '#1d4ed8',
      background: '#ffffff',
      text: '#1f2937',
      heading: '#1e3a8a',
      border: '#e5e7eb',
      highlight: '#3b82f6',
      success: '#10b981',
      warning: '#f59e0b',
      danger: '#ef4444',
    },
  },
  {
    id: 'fresh-green',
    name: 'Fresh Green',
    nameTamil: 'புதிய பச்சை',
    colors: {
      primary: '#16a34a',
      secondary: '#15803d',
      background: '#f0fdf4',
      text: '#1f2937',
      heading: '#14532d',
      border: '#bbf7d0',
      highlight: '#22c55e',
      success: '#10b981',
      warning: '#f59e0b',
      danger: '#ef4444',
    },
  },
  {
    id: 'elegant-purple',
    name: 'Elegant Purple',
    nameTamil: 'நேர்த்தியான ஊதா',
    colors: {
      primary: '#9333ea',
      secondary: '#7c3aed',
      background: '#faf5ff',
      text: '#1f2937',
      heading: '#581c87',
      border: '#e9d5ff',
      highlight: '#a855f7',
      success: '#10b981',
      warning: '#f59e0b',
      danger: '#ef4444',
    },
  },
  {
    id: 'dark-mode',
    name: 'Dark Mode',
    nameTamil: 'இருண்ட பயன்முறை',
    colors: {
      primary: '#f97316',
      secondary: '#ea580c',
      background: '#1f2937',
      text: '#f3f4f6',
      heading: '#ffffff',
      border: '#374151',
      highlight: '#fbbf24',
      success: '#10b981',
      warning: '#f59e0b',
      danger: '#ef4444',
    },
  },
];

export const FONT_OPTIONS = [
  { value: 'Inter', label: 'Inter (Default)' },
  { value: 'Poppins', label: 'Poppins' },
  { value: 'Roboto', label: 'Roboto' },
  { value: 'Open Sans', label: 'Open Sans' },
  { value: 'Lato', label: 'Lato' },
  { value: 'Montserrat', label: 'Montserrat' },
  { value: 'Raleway', label: 'Raleway' },
  { value: 'Playfair Display', label: 'Playfair Display (Elegant)' },
];